export default {
  REQUEST_PRODUCTS: "REQUEST_PRODUCTS",
  RECEIVE_PRODUCTS: "RECEIVE_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CHANGE_AMOUNT: "CHANGE_AMOUNT",
  TOGGLE_SIDE_MENU: "TOGGLE_SIDE_MENU"
}