export default {
  REQUEST_POSTS: "REQUEST_POSTS",
  PRODUCTS_FETCH_DATA_SUCCESS: "PRODUCTS_FETCH_DATA_SUCCESS",
  FETCH_PRODUCT_BY_ID: "FETCH_PRODUCT_BY_ID",
  FETCH_PRODUCTS_BY_PARAM: "FETCH_PRODUCTS_BY_PARAM",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CHANGE_AMOUNT: "CHANGE_AMOUNT",
}